services:
  server:
    ports:
      - 5678:5678
    build:
      context: ./services/server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - STORAGE_PATH=./storage
      - AGENCY_QUORUM_MIN=3

  client_0:
    volumes:
      - ./input:/input
      - ./output:/output
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_0
    depends_on:
      - server
    environment:
      - AGENCY_ID=0
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-0.csv
      - OUTPUT_FILE=/output/output_0.csv
      - BATCH_SIZE=32
  
  client_1:
    volumes:
      - ./input:/input
      - ./output:/output
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_1
    depends_on:
      - server
    environment:
      - AGENCY_ID=1
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-1.csv
      - OUTPUT_FILE=/output/output_1.csv
      - BATCH_SIZE=32

  client_2:
    volumes:
      - ./input:/input
      - ./output:/output
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_2
    depends_on:
      - server
    environment:
      - AGENCY_ID=2
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-2.csv
      - OUTPUT_FILE=/output/output_2.csv
      - BATCH_SIZE=32

  client_3:
    volumes:
      - ./input:/input
      - ./output:/output
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_3
    depends_on:
      - server
    environment:
      - AGENCY_ID=3
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-3.csv
      - OUTPUT_FILE=/output/output_3.csv
      - BATCH_SIZE=32

  client_4:
    volumes:
      - ./input:/input
      - ./output:/output
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_4
    depends_on:
      - server
    environment:
      - AGENCY_ID=4
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-4.csv
      - OUTPUT_FILE=/output/output_4.csv
      - BATCH_SIZE=32

  client_5:
    volumes:
      - ./input:/input
      - ./output:/output
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_5
    depends_on:
      - server
    environment:
      - AGENCY_ID=5
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-5.csv
      - OUTPUT_FILE=/output/output_5.csv
      - BATCH_SIZE=32
      